### ISSUE TITLE
Prebuilt packages / run on another machine

### ISSUE THREAD

**Issue by Maniues** [dotdevelop/dotdevelop#132]
Hello,
I would like to use dotdevelop without the need to compile it every time on each computer.
Unfortunately, dotdevelop binaries do not work when transferred to a machine other than the one on which they were created.

What components are needed to run dotdevelop? Do I need to copy the entire code folder or just main/build/bin?
What version of .NET do I need to run? Only mono? Mono and .NET Core (what version?)?

Is there a plan to provide binary versions of dotdevelop for everyone to download? This could already be a working IDE for .NET/C#, despite some bugs. Additionally, it would be easier for users to evaluate and detect bugs if binaries were provided rather than having to be compiled.

**Comment by Mr-Precise** [comment]
install dependenties based on  build instructions [dotdevelop
/Building.md](https://github.com/dotdevelop/dotdevelop/blob/main/Building.md) but with a nuance.
Configure with prefix:
`./configure --profile=gnome --prefix=/usr`
`make`
Then you can install "in a local directory" like that:
```make install DESTDIR=`pwd`/dotdevelop-local-install```
this will install .desktop files, translation files, etc.
After copy binaries `cp -rf main/build/* dotdevelop-local-install/usr/lib/monodevelop/`
Theoretically, this installation can be made a debian package adding configuration DEBIAN/control by entering the package name, version, dependencies, etc.
I already tried to do something similar by making an experimental own build [ubuntu package](https://github.com/Mr-Precise/dotdevelop/releases/tag/v2023.8.18) for ubuntu 20.04

**Comment by lextm** [comment]
@Maniues Launch two instances and then attach one to debug the other. Then you can learn why the crashes occur and report back here.

**Comment by lextm** [comment]
@Maniues MonoDevelop was once shipped solely via flatpak, and that was a nightmare. So, any attempt to use such packaging solutions should be very careful as this is an IDE, not an ordinary app.

**Comment by lextm** [comment]
@Maniues MonoDevelop was meant for full Mono development support, so I don't see anything wrong to require mono-complete package to be installed in advance.

The embedded runtime used by JetBrains or Eclipse saves you no disk space at all, so why bother?

**Comment by lextm** [comment]
> The embedded runtime in IntelliJ and Eclipse means I don't have to deal with dependencies and "I want another Mono version but my IDE won't let me" problems. Now we also have .NET Core, and to compile DotDevelop according to your instructions I need .NET Core 3.1, 5 and 6.

I think we have to cut your concerns into smaller pieces. Otherwise, there won't be meaningful results.

1. You seem to want install MonoDevelop from this repo with worrying about dependencies. That's fairly good feature request and nobody denies it. MonoDevelop was easy to install historically when the Mono team was able to distribute precompiled binaries in different package systems. However, those days were long gone. The current maintainers and others who monitor this repo might not be able to revive the previous packaging infrastructure right now, so you have to acquire all dev dependencies and compile from source code yourself.

1. You seem to want to target multiple versions of Mono by saying "I want another Mono version but my IDE won't let me". That's not very true, as different versions of Mono can be installed in parallel as [documented here](https://www.mono-project.com/docs/compiling-mono/parallel-mono-environments/). However, the experience might be different from what you expected. Usually you acquire a stable release of MonoDevelop and its dependent Mono bits from a package system, and then you install older/newer Mono in parallel. I don't believe many developers (except who developed Mono itself) went down this path, and the proof is that such documentation was often out-of-date or missed important steps.

1. You seem to dislike the fact that to build MonoDevelop from this repo you need not only Mono but many .NET Core SDK versions. There are historical reasons behind that, as the source code contains bits that rely on those SDK versions to compile. Cleanup is required, but no one actually moves forward there (or I didn't know yet). Those SDKs were not required to build MonoDevelop before the Mono team started to take in .NET Core/Standard bits. If you don't like that MonoDevelop from this repo relies on so many runtimes/SDKs, you might help migrate it fully to .NET 7 or 8. Microsoft's VS for Mac proved that's a feasible path, but sadly no more information was shared.

1. "If it weren't for the fact that DotDevelop relies on Mono" is kind of unfair to me. When Mono was actively maintained and shipped with latest MSBuild from Microsoft, there was nothing wrong to rely on Mono and benefit from it the support of multiple .NET Core SDKs. It only became a pain when Mono went inactive and the latest MSBuild is only available in .NET 7 or 8 SDK. Again, like the previous, you might help the migration, or MonoDevelop from this report won't be able to support .NET 7 and above.
