### ISSUE TITLE
dotnetcore / netstandard projects not working if .net 5.0 (dotnet 5) is installed

### ISSUE THREAD

**Issue by lytico** [dotdevelop/dotdevelop#40]
working with 
dotnetcore / netstandard projects (any version)
fails if .net 5.0 (dotnet 5) is installed

errors:

build:
```
/usr/share/dotnet/sdk/5.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(5,5): Error MSB4186: Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetFrameworkIdentifier' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order. (MSB4186) (md_test_dotnetcore)
```

nuget:
```
Getting restore information for project /home/data/Work/Programming/dotdevelop/TestProjects/md_test_dotnetcore/md_test_dotnetcore/md_test_dotnetcore.csproj
/usr/share/dotnet/sdk/5.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(54,5) : error MSB4186: Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetFrameworkIdentifier' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order.
Unable to create package spec for project. '/home/data/Work/Programming/dotdevelop/TestProjects/md_test_dotnetcore/md_test_dotnetcore/md_test_dotnetcore.csproj'
```

project options:

![image](https://user-images.githubusercontent.com/1479980/103683310-53815c80-4f8a-11eb-9d35-a47bc0ee37ec.png)

**Comment by lytico** [comment]
issue branch is:

https://github.com/dotdevelop/dotdevelop/commits/dotdevelop_oe_8.6_Nuget_5.8

**Comment by lytico** [comment]
hint: https://github.com/mono/monodevelop/pull/752

**Comment by lextm** [comment]
Can also be related to https://github.com/mono/mono/issues/20250 It seems not easy to get everything around .NET 5 to work well with Mono without a Mono update.

**Comment by hwthomas** [comment]
The situation has progressed now with the latest versions of mono, msbuild, and .NET5.0
On ubuntu 20.04 (and similarly on fedora) the software environment is:-

    dotnet --info ...  
      host 5.0.11
      sdk  5.0.403, 3.1.414
      run  5.0.11   3.1 414
      
    mono --version    6.12.0.147
    msbuild -version  16.10.1 for Mono.  

A simple netcoreapp3.1 project can be created with VS2019 or from the command line with ``dotnet new console --name=net31``, and ``net31.csproj`` can be loaded, edited, and built successfully in dotdevelop.  This produces, in folder ``net31/bin/Debug/netcoreapp3.1`` an executable file ``net31``, and a dll file ``net31.dll`` which can be run from the command line with either ``mono net31.dll`` *or* ``dotnet net31.dll``.  

In order to debug it from dotdevelop, it is necessary to create a soft link in that folder with `ln -s net31.dll net31.exe` and the program can then be debugged as normal (thanks to @tommih for that discovery).  

More complex netcoreapp3.1 projects can also be built and debugged successfully in dotdevelop - for example https://github.com/dotdevelop/xwt which has test apps for .NETFramework 4.7.2 (GtkTest) and netcoreapp3.1 (GtkSharpTest)  

For net5.0 projects, create a simple console project with ``dotnet new console --name=net50``.  When ``net50.csproj`` is loaded into dotdevelop, the ``net50/obj/project.assets.json`` file is re-written, so that ``targets`` and ``frameworks`` entries are shown as ``.NETFramework, Version = v5.0`` instead of ``net5.0``.  However, with the project still loaded, if the original version of ``project.assets.json`` is copied back in, the project can be built without error.  Again, by making a soft link with ``ln -s net50.dll net50.exe`` the net 5.0 project can also be debugged as normal.  

These results point to a number of obvious areas for work, but it now seems that there is no intrinsic bar to running .NET5.0 projects in dotdevelop.

**Comment by pracplayopen** [comment]
AM able to build latest dotdevelop- it was simpler and less error prone than last time we built monodevelop, good job.
(notice it still builds monodevelop.exe, happy to fix this if it will help us turn corner on this project ;).

that said, the success building and running doesn't seem to extend to building any dotnet projects, at least not for me.

AM NOT able to build any target-framework > 4.8 w/dotdevelop, even when the same file works perfectly w/mono (or dotnet).

what I tried:
* have many projects that build on mono and dotnet just fine, but error building in dotdevelop
* also created a new vanilla .netstandard2.0 project from dotdevelop standard templates, this worked as expected but will not build

all projects-assuming they build in both mono and dotnet from cli- give same errors in dotdevelop.

the errors shown in both projects (pre-existing, and netstandard2.0 empty project from template) are:
1. "MSB4236 WorkloadAutoImportPropsLocator could not be found".  that is described by [this issue](https://github.com/dotnet/sdk/issues/17461) and the workaround seems to work... setting environment variable to disable this prior to starting monodevelop 'MSBuildEnableWorkloadResolver=false monodevelop &'
1. after fixing WorkloadAutoImport error, now see this error in every project:  
> error MSB4186: Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetFrameworkIdentifier' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order.

Also in the project properties, it does not display any target framework over 4.8 (it lists the long unexpanded variable above as a target framework, even though it's not present in the template netstandard project).

As mentioned I can build same project from cli w/mono:

```
$ nuget restore
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
Restoring packages for /home/user/work/src/testnet2/projects/testnet2/testnet2.csproj...
Committing restore...
Generating MSBuild file /home/user/work/src/testnet2/projects/testnet2/obj/testnet2.csproj.nuget.g.props.
Generating MSBuild file /home/user/work/src/testnet2/projects/testnet2/obj/testnet2.csproj.nuget.g.targets.
Writing assets file to disk. Path: /home/user/work/src/testnet2/projects/testnet2/obj/project.assets.json
Restore completed in 417.26 ms for /home/user/work/src/testnet2/projects/testnet2/testnet2.csproj.
$ msbuild /p:Configuration=Release
  testnet2 -> /home/user/work/src/testnet2/projects/testnet2/bin/Release/netstandard2.0/testnet2.dll
Build succeeded.
    0 Warning(s)
    0 Error(s)
```

and dotnet
```
$ dotnet build /p:Configuration=Release
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/user/work/src/temp/projects/testnet2/testnet2.csproj (in 190 ms).
testnet2 -> /home/user/work/src/temp/projects/testnet2/bin/Release/netstandard2.0/testnet2.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

this is ubuntu 20.04 w/donet 5 and 6 installed:

``` 
$ mono --version
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:22:56 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)


$ msbuild -version
Microsoft (R) Build Engine version 16.6.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.6.0.60701
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  20.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]
  6.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info


```

examples here are slightly different than @hwthomas' above (netstandard2.0 libraries vs 5.0 console app example).... but just to give you an idea how simple the project file from the netstandard library is.... this is it:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>

```

this file (w/no packages or code) is what is generating above error. (as are all other working projects)

thx

**Comment by hwthomas** [comment]
@pracplayopen  
>    after fixing WorkloadAutoImport error, now see this error in every project:
>    error MSB4186: Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')".  
> Method '[MSBuild]::GetTargetFrameworkIdentifier' not found. Static method invocation should be of the form: ...  

Have a look at Issue #75 for what's causing this.  The changes in #77 will allow you to see and change the `TargetFramework` in your `netstandard2.0` example but they've not been merged yet because even more problems then become apparent.  One of these is covered by #79, but progress (and familiarity) with the NuGet interface is slow at present.  Feel free to poke around if you have any time (and interest!).   

Thanks for reporting what you've found so far - it all helps.

**Comment by hwthomas** [comment]
@pracplayopen Thanks for the offer of testing.  There are a number of pending Pull Requests, of which the `ns2.1_fix` is just one.  

You might also like to look at the others, which are all 'cumulative', in that each branch is rebased to the tip of the previous one. In order, they are:-  

#77 , #87  , #90  , #91 

I've also combine all together into a single branch `hwt-dev` in my fork (https://github.com/hwthomas/dotdevelop/tree/hwt-dev) and, taken together, they allow DotDevelop to create, build, and debug (with the SamsungNetCoreDbg) `.net5.0` and `.net6.0` projects.  
It is early days yet (these PRs have not yet been accepted) but if you have time to try them out, I'd be very interested in how far things may have (hopefully!) progressed.  All feedback is very welcome!

**Comment by pracplayopen** [comment]
@hwthomas apologies that i haven't found resources for this.

to be honest after buying jetbrains rider licenses and using it for a while, hard to imagine going back to microsoft-supported monodevelop, much less an even smaller project.   not for a couple of years anyways.  it's the closest thing to being able to run vs pro natively on linux, including monodevelop in it's hay day.

perhaps this will change but wanted to set expectations properly since did not do so well last time.

good luck and it seems like you've got a good handle on how to keep it workable and hopefully make it simpler/cheaper for you to maintain.

best

**Comment by hwthomas** [comment]
@pracplayopen  thanks for letting us know that you haven't been able to do any more netstandard testing.  I'm sure all these things will get done as and when dotdevelop becomes more stable, and we get a longer-term roadplan together. Good to hear that you are having a good experience with jetbrains rider.  If you find any 'must-have' workflow suggestions as a result, do feed them back into dotdevelop - we may one day be able to use them!

**Comment by pracplayopen** [comment]
sure, tho i wouldn't recommend you try to copy specific features in pro ides atm.

the biggest thing you can do as the lead is improve the contributor workflow.   being able to have new devs always have a stable and nightly branches to build, docs to guide to right spot, and pain points that are hard to maintain.

so far you're doing the right things that i can tell.   imho tho you still need to get a lot more contributors.   features might bring a dev or two but contributors will have a much bigger multipler effect.  anyways my 02

looking forward to seeing how this develops!
