### ISSUE TITLE
MonoDevelop.VersionControl.Git crashes with a SIGSEGV

### ISSUE THREAD

**Issue by muhammadsammy** [dotdevelop/dotdevelop#52]
Thanks for making this IDE compile again!
I get an error message `The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception` whever I open any file of in a solution with the IDE.
I see that #30 got closed, so is it related to this error or the editor is not ready yet?

## Environment data

Built from the `main` branch.

dotnet --info output:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by lytico** [comment]
thanks for trying! 
what debian you are using? I want to try on your used os version.
on mint, it works.

you can try to disable the git-addin with Tools->Extensions->Versioncontrol->GitSupport 
and see if the editor works then.

Another hint would be:
```
rm -R home/<yourusername>/.nuget/packages/libgit2sharp
rm -R home/<yourusername>/.nuget/packages/libgit2sharp.nativebinaries
```
and compile again.

BUT
you have NET SDK 5 installed, so you probably run into this issue: #40

**Comment by muhammadsammy** [comment]
> what debian you are using? I want to try on your used os version.
> on mint, it works.
>

I'm using Debian sid

> you can try to disable the git-addin with Tools->Extensions->Versioncontrol->GitSupport
> and see if the editor works then.
> 

That fixed the issue and the editor is now working. Thanks!

> Another hint would be:
> 
> ```
> rm -R home/<yourusername>/.nuget/packages/libgit2sharp
> rm -R home/<yourusername>/.nuget/packages/libgit2sharp.nativebinaries
> ```
> 
> and compile again.
> 

I tried this multiple times, before and after removing .NET5 and it still does not fix the issue until I disable `Git Support` extension. 
Since it's working on mint and ubuntu, It may be a problem specific to debian sid.

> BUT
> you have NET SDK 5 installed, so you probably run into this issue: #40
>

Yes, I ran into the same issue and it got resolved after removing .NET5. Thank you!

**Comment by Molytho** [comment]
> Since it's working on mint and ubuntu, It may be a problem specific to debian sid.

I complied it on debian buster and it isn't working on either, so it is some sort of debian specific bug.

dotnet --info output:
```
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.405
 Commit:    3fae16e62e

Laufzeitumgebung:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.405/

Host (useful for support):
  Version: 3.1.11
  Commit:  f5eceb8105

.NET Core SDKs installed:
  3.1.405 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
mono --version output:
```
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:28:17 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

**Comment by lytico** [comment]
See: https://github.com/dotdevelop/libgit2sharp/issues/2
I'try to solve it there and create a package working  on debian

**Comment by lytico** [comment]
@Molytho @muhammadsammy  this branch worked for me on a fresh debian 10 install:

https://github.com/dotdevelop/dotdevelop/tree/dd/issues/52

can you confirm?

**Comment by muhammadsammy** [comment]
Yes, can confirm it working on debian sid. thanks

**Comment by Molytho** [comment]
Sorry, can't confirm it. Now it crashes with a SIGSEGV. I will look into it when i have more time.

**Comment by Molytho** [comment]
It's not an issue with libgit2sharp.nativebinaries. The arguments being passed to git_status_list_new (the first native libgit2 method in backtrace) are invalid, so this might be an issue in libgit2sharp.

**Comment by Molytho** [comment]
The issue lies somewhere in the marshalling. It is caused by the native call [here](https://github.com/libgit2/libgit2sharp/blob/3d7276275e8ea9dce324e437760c31e69b5ec10c/LibGit2Sharp/RepositoryStatus.cs#L61).
While marshalling the coreOptions argument ([GitStatusOptions: libgit2sharp](https://github.com/libgit2/libgit2sharp/blob/3d7276275e8ea9dce324e437760c31e69b5ec10c/LibGit2Sharp/Core/GitStatusOptions.cs#L7) -> [git_status_options: libgit2](https://github.com/libgit2/libgit2/blob/523d5e0f6865a1c1aea791d21b5edc58a3ed745d/include/git2/status.h#L170)) the baseline field which is not available in GitStatusOptions gets a valid pointer value. This makes libgit2 believe that the git_tree* is valid leading to a read of an invalid pointer value and finally to an invalid memory access.

**Comment by lytico** [comment]
the libgit2sharp - nuget used comes from this tree: https://github.com/dotdevelop/libgit2sharp/tree/dd/issues/2
the issue is https://github.com/dotdevelop/libgit2sharp/issues/2

**Comment by hwthomas** [comment]
This is just to confirm that this issue is not confined to debian - the same occurs on ubuntu, fedora and Arch.

Using the current ``main`` branch (@ecbe8d3), ``dotdevelop`` crashes consistently with a SIGSEGV.  

Eg - open the (fairly complex) Solution https://github.com/dotdevelop/xwt   

The solution can be loaded, and all packages restored successfully, but if the Solution pad is opened the crash occurs. Disabling the Version Control Git support extension from the Tools menu allows the Solution pad to be opened and the Xwt TestApps project to be edited and run without problems.  

However, simple projects such as a Gtk# "Hello World" test (Framework 4.7.2) work OK even with the VC extension enabled.   

$ dotnet --info details (abbreviated) are:-  

    .NET Core SDK (reflecting any global.json):
      Version:   3.1.403
    Host (useful for support):
      Version: 3.1.9
    .NET Core runtimes installed:
      Microsoft.NETCore.App 2.2.8  
      Microsoft.NETCore.App 3.1.9  

I was about to raise a new Issue, but then noticed this same problem, together with your further investigations, tucked away as if it was only a debian sid/buster issue. Perhaps it's worth renaming it?

**Comment by hwthomas** [comment]
I've had the following (different) results with recent versions of ``dotdevelop`` 

In all cases the repository to be checked out is https://github.com/dotdevelop/xwt     

``dotdevelop_oe_8.4.3.12``  Fails to check out github repo, with error ``invalid Version 0 on git_proxy_options``  

``dotdevelop_oe_8.6``  Checks out github repo successfully with all of the available protocols.  

This then Loads the repo and all packages are restored OK, but crashes with a ``SIGSEGV`` when the Solution pad is opened.

However, ``dotdevelop_oe_8.4.3.12`` **can** open this repo/solution without crashing, and also build and run it OK.

``dotdevelop_main``  commit ``ecbe8d3cc1a`` (latest).  Checks out repo OK using ``git://`` protocol, but fails with error `there is no TLS stream available` using `http://` or `https://` protocols.  Like ``dotdevelop_oe_8.6``, crashes with ``SIGSEGV`` if Solution pad is clicked.  

I've no facilities for debugging any of these versions further (dotdevelop won't yet build itself!) but perhaps the differences between these versions might suggest something?

**Comment by lytico** [comment]
> Checks out repo OK using ``git://`` protocol, but fails with error `there is no TLS stream available` using `http://` or `https://` protocols.

new issue here: https://github.com/dotdevelop/libgit2sharp/issues/3

in the testrun, the error shows up, see: https://github.com/dotdevelop/libgit2sharp/runs/1770928010?check_suite_focus=true
